---
engines:
 rubocop:
   exclude_paths:
     - config/engines.yml
 duplication:
   exclude_paths:
     - config/engines.yml
 metric:
   exclude_paths:
     - config/engines.yml
 coverage:
   exclude_paths:
     - config/engines.yml
exclude_paths:
  - 'modules/server/src/main/resources/static/**' 