package es.weso.rdfshape.buildinfo

/** This object is written by hand but should be generated by sbt-buildinfo 
    TODO: Find the reason that it fails
 */
/* 
case object BuildInfo {
  val name: String = "rdfshape"
  val version: String = "0.1.24"
  val scalaVersion: String = "2.13.0"
  val sbtVersion: String = "1.2.8"
  val rdfshapeVersion: String = "0.1.75"
  override val toString: String = "name: %s, version: %s, scalaVersion: %s, sbtVersion: %s" format (name, version, scalaVersion, sbtVersion)
}
 */
