addSbtPlugin("com.codecommit"   % "sbt-github-actions"  % "0.14.2")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"        % "1.2.0")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"       % "0.11.0")
addSbtPlugin("com.github.sbt"     % "sbt-unidoc"          % "0.5.0")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"      % "1.5.10")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.9")
addSbtPlugin("io.spray"         % "sbt-revolver"        % "0.9.1")
addSbtPlugin("org.lyranthe.sbt" % "partial-unification" % "1.1.2")
// addSbtPlugin("com.simplytyped"  % "sbt-antlr4"          % "0.8.1")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.4.0")
addSbtPlugin("org.scalameta"    % "sbt-mdoc"            % "2.3.5")
