prefix foaf: <http://xmlns.com/foaf/0.1/> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix l4a: <http://labels4all.info/ns/> 
prefix lexlang: <http://lexvo.org/id/iso639-1/> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 

SELECT ?uri ?label ?vs 
WHERE {
	?x l4a:resource ?uri .
	?x l4a:label ?label .
	?x l4a:sumVotes ?vs . 
	?x l4a:language lexlang:es .
}
# GROUP BY ?uri
