package es.weso.server

import java.util.concurrent.Executors

import cats.implicits._
import cats.data.EitherT
import cats.effect._
import results._

import scala.concurrent.ExecutionContext.global
import es.weso.rdf.PrefixMap
import es.weso.rdf.jena.RDFAsJenaModel
import es.weso.schema._
import es.weso.server.Defaults._
import es.weso.utils.FileUtils
import es.weso.rdf.RDFReasoner
import es.weso.rdf.nodes._
import io.circe._
import org.http4s._
import org.log4s.getLogger
import es.weso.uml._
import es.weso.schemaInfer._
import es.weso.server.helper.DataFormat
import es.weso.shapeMaps.{NodeSelector, ShapeMap}
import org.http4s.client.{Client, JavaNetClientBuilder}
import es.weso.shacl.converter.Shacl2ShEx
import es.weso.shex.converter.ShEx2Shacl
import es.weso.utils.json.JsonUtilsServer._
import es.weso.server.Defaults._
import org.http4s.dsl._
import scala.util.Try
import es.weso.utils.IOUtils._
import es.weso.shapeMaps.ResultShapeMap

object ApiHelper {

  private val logger = getLogger
  private val NoTime = 0L

  // TODO: Get options from user as parameters
  private val options = PlantUMLOptions(watermark = Some("Generated by [[http://rdfshape.weso.es rdfshape]]"))

  /**
    * Get base URI
    * @return default URI obtained from current folder
    */
  private[server] def getBase: Option[String] = Defaults.relativeBase.map(_.str)

  private[server] def prefixMap2Json(pm: PrefixMap): Json = {
    Json.fromFields(pm.pm.map { case (prefix, iri) => (prefix.str, Json.fromString(iri.getLexicalForm)) })
  }

  private[server] def resolveUri(baseUri: Uri, urlStr: String): IO[String] = {
    println(s"Handling Uri: $urlStr")
    // TODO: handle timeouts
    Uri.fromString(urlStr).fold(
      fail => {
        logger.info(s"Error parsing $urlStr")
        IO.raiseError[String](new RuntimeException(s"Error resolving ${urlStr} as URL: ${fail.message}"))
      },
      uri => {
        // TODO: The following code is unsafe...
        implicit val cs: ContextShift[IO] = IO.contextShift(global)
        implicit val timer: Timer[IO] = IO.timer(global)
        val blockingPool = Executors.newFixedThreadPool(5)
        val blocker = Blocker.liftExecutorService(blockingPool)
        val httpClient: Client[IO] = JavaNetClientBuilder[IO](blocker).create
        val resolvedUri = baseUri.resolve(uri)
        logger.info(s"Resolved: $resolvedUri")
        httpClient.expect[String](resolvedUri)
      }
    )
  }

  private[server] def schemaConvert(optSchema: Option[String],
                  optSchemaFormat: Option[String],
                  optSchemaEngine: Option[String],
                  optTargetSchemaFormat: Option[String],
                  optTargetSchemaEngine: Option[String],
                  base: Option[String]): EitherT[IO, String, Option[String]] =
   optSchema match {
    case None => either2es(None.asRight[String])
    case Some(schemaStr) => {
      val schemaFormat = optSchemaFormat.getOrElse(Schemas.defaultSchemaFormat)
      val schemaEngine = optSchemaEngine.getOrElse(Schemas.defaultSchemaName)
      // val x: EitherT[IO,String,Schema] = Schemas.fromString(schemaStr, schemaFormat, schemaEngine, base)
      for {
        schema <- Schemas.fromString(schemaStr, schemaFormat, schemaEngine, base)
        result <- schema.convert(optTargetSchemaFormat,optTargetSchemaEngine,base.map(IRI(_)))
      } yield Some(result)
    }
  }

  private[server] def validate(rdf: RDFReasoner,
                               dp:DataParam,
                               schema: Schema,
                               sp: SchemaParam,
                               tp: TriggerModeParam,
                               relativeBase: Option[IRI]
              ): IO[(Result, Option[ValidationTrigger], Long)] = {
    println(s"APIHelper: validate")
    val base = relativeBase.map(_.str) // Some(FileUtils.currentFolderURL)
    val triggerMode = tp.triggerMode
    val (optShapeMapStr, eitherShapeMap) = tp.getShapeMap(rdf.getPrefixMap,schema.pm)
    ValidationTrigger.findTrigger(triggerMode.getOrElse(Defaults.defaultTriggerMode),
         optShapeMapStr.getOrElse(""), base, None, None,
         rdf.getPrefixMap, schema.pm) match {
         case Left(msg) =>
            err(s"Cannot obtain trigger: $triggerMode\nshapeMap: $optShapeMapStr\nmsg: $msg")
         case Right(trigger) => for {
             startTime <- IO { System.nanoTime() }
             result <- schema.validate(rdf, trigger)
             endTime <- IO { System.nanoTime() }
             time: Long = endTime - startTime
         } yield (result,Some(trigger),time)
    }
  }

  private[server] def validateStr(data: String,
                                  optDataFormat: Option[DataFormat],
                                  optSchema: Option[String],
                                  optSchemaFormat: Option[String],
                                  optSchemaEngine: Option[String],
                                  tp: TriggerModeParam,
                                  optInference: Option[String],
                                  relativeBase: Option[IRI]
                                 ): IO[(Result, Option[ValidationTrigger], Long)] = {
    val dp = DataParam.empty.copy(
      data = Some(data),
      dataFormatTextarea = optDataFormat,
      inference = optInference
    )
    val sp = SchemaParam.empty.copy(
      schema = optSchema,
      schemaFormatTextArea = optSchemaFormat,
      schemaEngine = optSchemaEngine
    )
    
    val result: ESIO[(Result, Option[ValidationTrigger], Long)] = for {
     pair <- dp.getData(relativeBase)
     (maybeStr,rdf) = pair
     pair <- io2es(sp.getSchema(Some(rdf)))
     (_,eitherSchema) = pair
     schema <- either2es(eitherSchema)
     result <- io2es(validate(rdf,dp,schema,sp,tp, relativeBase))
    } yield result

    result.value.flatMap(_.fold(e => err(e),IO.pure(_)))
  }


  private def err(msg: String) =
    IO((Result.errStr(s"Error: $msg"), None, NoTime))

  private[server] def query(data: String,
            optDataFormat: Option[DataFormat],
            optQuery: Option[String],
            optInference: Option[String]
           ): IO[Json] = {
    optQuery match {
      case None => IO(Json.Null)
      case Some(queryStr) => {
        val dataFormat = optDataFormat.getOrElse(defaultDataFormat)
        val base = Some(IRI(FileUtils.currentFolderURL))
        for {
          basicRdf <- RDFAsJenaModel.fromChars(data, dataFormat.name, base)
          rdf <- basicRdf.applyInference(optInference.getOrElse("None"))
          json <- rdf.queryAsJson(queryStr)
        } yield json
      }
    }
  }

  private[server] def dataExtract(rdf: RDFReasoner,
                                  optData: Option[String],
                                  optDataFormat: Option[DataFormat],
                                  optNodeSelector: Option[String],
                                  optInference: Option[String],
                                  optEngine: Option[String],
                                  optSchemaFormat: Option[String],
                                  optLabelName: Option[String],
                                  relativeBase: Option[IRI],
                                 ): IO[DataExtractResult] = {
    val base = relativeBase.map(_.str)
    val engine = optEngine.getOrElse(defaultSchemaEngine)
    val schemaFormat = optSchemaFormat.getOrElse(defaultSchemaFormat)
    optNodeSelector match {
      case None => IO.pure(DataExtractResult.fromMsg("DataExtract: Node selector not specified"))
      case Some(nodeSelector) => {
        val es: ESIO[(Schema,ResultShapeMap)] = for {
          selector <- either2es(NodeSelector.fromString(nodeSelector, base, rdf.getPrefixMap()))
          eitherResult <- {
            println(s"Node selector: $selector")
            val inferOptions: InferOptions = InferOptions(
              inferTypePlainNode = true,
              addLabelLang = Some(Lang("en")),
              possiblePrefixMap = PossiblePrefixes.wikidataPrefixMap,
              maxFollowOn = 1,
              followOnLs = List(),
              followOnThreshold = Some(1),
              sortFunction = InferOptions.orderByIRI
            )
            io2es(SchemaInfer.runInferSchema(rdf, 
               selector, 
               engine, 
               optLabelName.map(IRI(_)).getOrElse(defaultShapeLabel),
               inferOptions
            ))
          }
          pair <- either2es(eitherResult)
          str <- io2es(pair._1.serialize("ShExC"))
          _ <- io2es(IO(println(s"Extracted; $str")))
        } yield {
          pair
        }
        for {
          either <- run_es(es)
        } yield either.fold(
          err => DataExtractResult.fromMsg(err),
          pair => {
            val (schema, resultShapeMap) = pair
            DataExtractResult.fromExtraction(optData, optDataFormat, schemaFormat, engine, schema, resultShapeMap)
          })
      }
    }
  }

  private[server] def convertSchema(schema: Schema,
                                    schemaStr: Option[String],
                                    schemaFormat: String,
                                    schemaEngine: String,
                                    optTargetSchemaFormat: Option[String],
                                    optTargetSchemaEngine: Option[String]
                                   ): IO[SchemaConversionResult] = {
    val result:ESIO[SchemaConversionResult] = for {
      resultStr <- schema.convert(optTargetSchemaFormat, optTargetSchemaEngine, None)
      sourceStr <- schemaStr match {
        case None => io2es(schema.serialize(schemaFormat))
        case Some(source) => ok_es(source)
      }
    } yield SchemaConversionResult.fromConversion(sourceStr, schemaFormat, schemaEngine, optTargetSchemaFormat, optTargetSchemaEngine, resultStr, ShapeMap.empty)

    for {
      either <- run_es(result)
    } yield either.fold(err => SchemaConversionResult.fromMsg(s"convertSchema: error: $err"), identity)
  }

  private[server] def shapeInfer(rdf: RDFReasoner,
                                 optNodeSelector: Option[String],
                                 optInference: Option[String],
                                 optEngine: Option[String],
                                 optSchemaFormat: Option[String],
                                 optLabelName: Option[String],
                                 relativeBase: Option[IRI],
                                 withUml: Boolean
                                ): ESIO[Json] = {
   val base = relativeBase.map(_.str)
   val engine = optEngine.getOrElse(defaultSchemaEngine)
   val schemaFormat = optSchemaFormat.getOrElse(defaultSchemaFormat)
   optNodeSelector match {
     case None => ok_es(Json.Null)
     case Some(nodeSelector) => {
       for {
         selector <- either2es(NodeSelector.fromString(nodeSelector, base, rdf.getPrefixMap()))
         eitherResult <- io2es {
           println(s"Selector: $selector")
           SchemaInfer.runInferSchema(rdf, selector, engine, optLabelName.map(IRI(_)).getOrElse(defaultShapeLabel))
         }
         result <- either2es(eitherResult)
         (schemaInfer, resultMap) = result
         maybePair <- if (withUml) either2es(Schema2UML.schema2UML(schemaInfer).map(Some(_))) else ok_es(None)
         svg = maybePair.map{ 
           pair => {
             val (uml,warnings) = pair
             uml.toSVG(options)
            }
        }
         str <- io2es(schemaInfer.serialize(schemaFormat))
       } yield Json.fromFields(
         List(
           ("inferedShape", Json.fromString(str)),
           ("format", Json.fromString(schemaFormat)),
           ("engine", Json.fromString(engine)),
           ("nodeSelector", Json.fromString(nodeSelector))
         ) ++
           maybeField(maybePair,"uml",
             (pair: (UML, List[String])) => {
               val (uml,warnings) = pair
               Json.fromString(uml.toPlantUML(options)) }
           ) ++
           maybeField(svg, "svg", Json.fromString(_))
       )
     }
   }
  }

  private[server] def dataFormatOrDefault(df: Option[String]): String =
    df.getOrElse(DataFormats.defaultFormatName)

  private[server] def dataInfoFromString(data: String, dataFormatStr: String): IO[Json] =  {
    val either: ESIO[Json] = for {
      dataFormat <- either2es(DataFormat.fromString(dataFormatStr))
      rdf <- io2es(RDFAsJenaModel.fromChars(data,dataFormat.name))
      json <- io2es(dataInfo(rdf, Some(data), Some(dataFormat)))
    } yield json

    either.fold(e => DataInfoResult.fromMsg(e).toJson, identity)
  }

  private[server] def dataInfo(rdf: RDFReasoner, data: Option[String], dataFormat: Option[DataFormat]): IO[Json] =  {
    val either: ESIO[DataInfoResult] = for {
      numberStatements <- io2es(rdf.getNumberOfStatements)
      preds <- stream2es(rdf.predicates)
    } yield DataInfoResult.fromData(data, dataFormat, preds.toSet, numberStatements, rdf.getPrefixMap)
    either.fold(e => DataInfoResult.fromMsg(e).toJson, _.toJson)
  }


  private[server] def getSchema(sv: SchemaValue): EitherT[IO,String,Schema] = {
    val schemaEngine = sv.currentSchemaEngine
    val schemaFormat = sv.currentSchemaFormat
    val schemaStr = sv.schema.getOrElse("")
    val base = Some(FileUtils.currentFolderURL)
    Schemas.fromString(schemaStr, schemaFormat, schemaEngine, base)
  }

  case class SchemaInfoReply(schemaName: Option[String],
                             schemaEngine: Option[String],
                             wellFormed: Boolean,
                             shapes: List[String],
                             shapesPrefixMap: List[(String,String)],
                             errors: List[String]
                             ) {
    def toJson: Json = Json.fromFields(List(
      ("schemaName", schemaName.fold(Json.Null)(Json.fromString(_))),
      ("schemaEngine", schemaEngine.fold(Json.Null)(Json.fromString(_))),
      ("wellFormed", Json.fromBoolean(wellFormed)),
      ("shapes", Json.fromValues(shapes.map(Json.fromString(_)))),
      ("shapesPrefixMap", Json.fromValues(shapesPrefixMap.map(pair => Json.fromFields(List(
        ("prefix", Json.fromString(pair._1)),
        ("uri", Json.fromString(pair._2))
      ))))),
      ("errors", Json.fromValues(errors.map(Json.fromString(_))))
    ))
  }

  object SchemaInfoReply {
    def fromError(msg: String): SchemaInfoReply = {
      println(s"SchemaInfoReply from $msg")
      SchemaInfoReply(None,None,false,List(),List(),List(msg))
    }
  }

  private[server] def schemaInfo(schema:Schema): Json = {
    val info = schema.info
    SchemaInfoReply(
      Some(info.schemaName),
      Some(info.schemaEngine),
      info.isWellFormed,
      schema.shapes,
      schema.pm.pm.toList.map{ case (prefix, iri) => (prefix.str, iri.str) },
      info.errors
    ).toJson
  }

  private[server] def schema2SVG(schema: Schema): (String,String) = {
    val eitherUML = Schema2UML.schema2UML(schema)
    eitherUML.fold(
      e => (s"SVG conversion: $e", s"UML Error convertins: $e"),
      pair => {
        val (uml,warnings) = pair
        // println(s"UML converted: $uml")
        (uml.toSVG(options), uml.toPlantUML(options))
      }
    )
  }

  private[server] def schemaCytoscape(schema:Schema): Json = {
    val eitherJson = for {
      pair <- Schema2UML.schema2UML(schema)
    } yield { 
      val (uml,warnings) = pair
      uml.toJson 
    }
    eitherJson.fold(
      e => Json.fromFields(List(("error", Json.fromString(s"Error converting to schema 2 JSON: $e")))),
      identity
    )
  }

  private[server] def schemaVisualize(schema:Schema): Json = {
    val (svg,plantuml) = schema2SVG(schema)
    val info = schema.info
    val fields: List[(String,Json)] =
      List(
        ("schemaName", Json.fromString(info.schemaName)),
        ("schemaEngine", Json.fromString(info.schemaEngine)),
        ("wellFormed", Json.fromBoolean(info.isWellFormed)),
        ("errors", Json.fromValues(info.errors.map(Json.fromString(_)))),
        ("parsed", Json.fromString("Parsed OK")),
        ("svg", Json.fromString(svg)),
        ("plantUML", Json.fromString(plantuml))
      )
    Json.fromFields(fields)
  }

  private[server] def getSchemaEmbedded(sp: SchemaParam): Boolean = {
    sp.schemaEmbedded match {
      case Some(true) => true
      case Some(false) => false
      case None => defaultSchemaEmbedded
    }
  }

  private[server] def mkJsonErr(msg: String) = Json.fromFields(List(("error", Json.fromString(msg))))
  
}